name = "shoesclean" 
main = "src/index.ts"
compatibility_date = "2024-01-20" 
account_id = "c8e7cc23b5cff77fbf9eef544cb35f69" 

[build]
command = "npm run build"

[vars]
ENVIRONMENT = "development"

[env.production]
vars = { ENVIRONMENT = "production" }

[dev]
port = 8787
local_protocol = "http"

[[d1_databases]]
binding = "DB" # Ini adalah bagaimana Anda akan mengaksesnya dalam kode Anda (misalnya, c.env.Shoesclean)
database_name = "shoesclean-db" # Nama database D1 Anda di dashboard Cloudflare
database_id = "b3f53077-8861-4f40-bc70-14b0a0d9348b" # ID Database yang Anda salin
migrations_dir = "migrations"